Changed travis-ci to use unittest2 for python 2.6, versions above use unittest discovery

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -44,7 +44,7 @@ fi
 
 
 echo "running unit tests..."
-python -m unittest cherrymusicserver.test.All
+python -m unittest discover --failfast -s ./cherrymusicserver/test -t .
 if [ $? != 0 ]; then
     echo "unit test(s) failed" >&2
     echo ^^^ `python -V` ^^^
@@ -52,13 +52,14 @@ if [ $? != 0 ]; then
 fi
 
 if [ $(command -v python2) ]; then
-    python2 -m unittest cherrymusicserver.test.All
+    python2 -m unittest discover --failfast -s ./cherrymusicserver/test -t .
+    if [ $? != 0 ]; then
+        echo "unit test(s) failed" >&2
+        echo ^^^ `python2 -V` ^^^
+        exit 1
+    fi
 fi
-if [ $? != 0 ]; then
-    echo "unit test(s) failed" >&2
-    echo ^^^ `python2 -V` ^^^
-    exit 1
-fi
+
 
 echo "checking dist metadata..."
 python ${PROJECTDIR}/setup.py check
