add target option and coverage to runtests
runtests [TARGET]

TARGET is assumed to be importable as "cherrymusicserver.TARGET" and
testable as "cherrymusicserver.test.test_TARGET". If not given, the
whole codebase will be tested, excluding a potential local copy of
cherrypy.

Coverage will be limited to the TARGET, if one is given. In that case, a
coverage of 100% is required to pass. If there is no TARGET, coverage
will be limited to the cherrymusicserver, cmbootstrap and audiotranscode
packages and require a minimum of 50% to pass. If the coverage plugin
can't be imported, no minimum coverage is required.

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -34,6 +34,10 @@
 ##############################################################################
 
 PROJECTDIR=`dirname $0`
+SPECIFIC_TEST="$1"
+
+TEST_EXCLUDE_REGEX='cherrypy'
+COVERAGE_OPTIONS="--with-coverage --cover-erase"
 
 if [ ! -d ${PROJECTDIR} -o ! -f ${PROJECTDIR}/cherrymusic ]; then
     echo "cannot find main script: 'cherrymusic'" >&2
@@ -41,25 +45,38 @@ if [ ! -d ${PROJECTDIR} -o ! -f ${PROJECTDIR}/cherrymusic ]; then
     exit 1
 fi
 
-echo "checking dist metadata..."
-python ${PROJECTDIR}/setup.py check
-if [ $? != 0 ]; then
-    echo "distribution metadata check failure" >&2
-    exit 1
+if [ $SPECIFIC_TEST ]; then
+    TEST_LOCATION="cherrymusicserver.test.test_${SPECIFIC_TEST}"
+    COVERAGE_TARGET="cherrymusicserver.${SPECIFIC_TEST}"
+    COVERAGE_OPTIONS="${COVERAGE_OPTIONS} --cover-package=${COVERAGE_TARGET} --cover-branches --cover-min-percentage=100"
+else
+    TEST_LOCATION=""
+    COVERAGE_TARGET="audiotranscode,cherrymusicserver,cmbootstrap"
+    COVERAGE_OPTIONS="${COVERAGE_OPTIONS} --cover-package=${COVERAGE_TARGET} --cover-min-percentage=50"
+
+    echo
+    echo "[distribution]: setup.py check"
+    python ${PROJECTDIR}/setup.py check
+    if [ $? != 0 ]; then
+        echo "distribution metadata check failure" >&2
+        exit 1
+    fi
+    echo "done."
 fi
-echo "done."
 
 
 # nosetests
 for i in "" "2" "3"; do
-    cmd="nosetests${i}"
-    if [ $(command -v $cmd) ]; then
-        echo "running ${cmd}:"
-        $cmd -e cherrypy
+    TESTER="nosetests${i}"
+    if [ $(command -v $TESTER) ]; then
+        RUN="${TESTER} -e ${TEST_EXCLUDE_REGEX} ${COVERAGE_OPTIONS} ${TEST_LOCATION}"
+        echo
+        echo "[${TESTER}]: ${RUN}"
+        $RUN
         if [ $? != 0 ]; then
-            failed="$failed $cmd"
+            failed="$failed $TESTER"
         else
-            passed="$passed $cmd"
+            passed="$passed $TESTER"
         fi
     fi
 done
